# Generated by Django 4.1.3 on 2022-11-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwalk', '0003_alter_folder_nb_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.CharField(default='rarity_by_default', max_length=20),
        ),
    ]
