# Generated by Django 4.1.3 on 2022-11-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwalk', '0005_rename_folder_inventory_alter_inventory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='password',
            field=models.CharField(default='pseudo_by_default', max_length=20),
        ),
    ]
