# Generated by Django 4.1.3 on 2022-11-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwalk', '0006_player_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(default='password_by_default', max_length=20),
        ),
    ]
